// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.OrderMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class table_rebuild2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(table_rebuild2));
        
        string IMigrationMetadata.Id
        {
            get { return "202504290933193_table_rebuild2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
