// <auto-generated />
namespace eUseControl.BusinessLogic.Migrations.OrderMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class test333 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test333));
        
        string IMigrationMetadata.Id
        {
            get { return "202505121923279_test333"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
